---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: invoice-api
  namespace: jenkins-workers
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: invoice-api
  namespace: airflow-workers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: invoice-api
  namespace: invoice-api
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: invoice-api
  namespace: invoice-api-dev
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: invoice-api
  namespace: invoice-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: invoice-api
subjects:
  - kind: ServiceAccount
    name: invoice-api
    namespace: jenkins-workers
  - kind: ServiceAccount
    name: invoice-api
    namespace: airflow-workers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: invoice-api
  namespace: invoice-api-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: invoice-api
subjects:
  - kind: ServiceAccount
    name: invoice-api
    namespace: jenkins-workers
  - kind: ServiceAccount
    name: invoice-api
    namespace: airflow-workers

